### ISSUE TITLE
Wrong handling of GetFeature properties due to multiple FeatureType

### ISSUE THREAD

**Issue by eblondel** [virtual-repository/virtual-ows#7]
The issue below was reported:

```
Caused by: java.lang.IllegalArgumentException: The xml does not describe the same type of feature: 
 Expected: _FeatureCollection
FeatureCollection
_Coverage
_ContinuousCoverage
_DiscreteCoverage
Observation
DirectedObservation
DirectedObservationAtDistance
eez

But was: ExceptionReport
 at org.geotoolkit.feature.xml.jaxp.JAXPStreamFeatureReader.read(JAXPStreamFeatureReader.java:204)
 at org.geotoolkit.feature.xml.jaxp.JAXPStreamFeatureReader.read(JAXPStreamFeatureReader.java:131)
 at org.virtual.ows.WfsReader.retrieve(WfsReader.java:43)
 at org.virtual.ows.WfsReader.retrieve(WfsReader.java:1)
 at org.virtualrepository.impl.Repository$1.call(Repository.java:291)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
```

**Comment by eblondel** [comment]
@fabiosimeoni  After investigation, it seems it was inherited from recent modifications in the Geotoolkit repository, where new types were supported. As side-effet in ``virtual-ows``, this resulted in adding to the ``GetFeature`` additional ``properties`` not actually part of the real ``feature type`` considered, leading to an ``ExceptionReport`` (ie a wrong ``GetFeature`` request)

Despite these changes in Geotk, it highlighted the need to modify the ``typesFor`` method in the ``WfsClient`` with a ``typeFor`` method, where the real ``feature type`` targeting the data is filtered out, other feature types are skipped.

The method ``typeFor`` get the list of ``feature types`` and filters to retain the one of interest. For the time being, the ``filter`` is based on ``asset`` and ``feature type`` name comparison. It's still not clear if this can be generalized. To notice that the ``feature type`` of interest seems to be the last of the list. I'm going to check with ``geotk`` team if it's more reasonable to base filter on this rule.

**Comment by eblondel** [comment]
Thanks @fabiosimeoni for the fix https://github.com/virtual-repository/virtual-ows/commit/ec27c48ed2f01d5575a0498d080a25aa7ba2d16a

Closing this one
